name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: 'pascalgn/automerge-action@0.74'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: 'automerge'
          MERGE_METHOD: 'squash'
          MERGE_FORKS: 'false'
          MERGE_RETRIES: '6'
          MERGE_RETRY_SLEEP: '10000'
          UPDATE_LABELS: ''
          UPDATE_METHOD: 'rebase'
